print('Siapa Kamu?')
fName = input()
print('hi, welcome bro/sis ' + fName)
print('jumlah huruf dinamamu adalah : ')
print(len(fName))
print('Umur Berapa Kamu?')
yAge = input()
print('kamu akan berumur '+ str(int(yAge) + 1) + ' tahun, pada tahun depan')
